name: mcp-demo-floci
services:
  floci:
    image: floci/floci:2.1.0@sha256:f5aa8c18302cedb4f2385f5c4e455b3efc77fee6bf7b6e5d1712b2817ba102db
    container_name: mcp-demo-floci
    ports:
      - "127.0.0.1:14566:4566"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - state:/app/data
    environment:
      FLOCI_STORAGE_MODE: hybrid
      FLOCI_STORAGE_PERSISTENT_PATH: /app/data
      FLOCI_STORAGE_PRUNE_VOLUMES_ON_DELETE: "true"
      FLOCI_SERVICES_DOCKER_NETWORK: mcp-demo-floci
      FLOCI_SERVICES_EKS_DOCKER_NETWORK: mcp-demo-floci
      FLOCI_SERVICES_EKS_MOCK: "false"
      FLOCI_SERVICES_EKS_ECR_REGISTRY_MIRROR: "false"
      FLOCI_SERVICES_ECR_ENABLED: "false"
      FLOCI_SERVICES_EKS_DEFAULT_IMAGE: rancher/k3s:v1.35.8-k3s1@sha256:59fe491fd3b73204e499e40b325240d85c42c7189c3ae50150d37b78243f3b32
      FLOCI_SERVICES_EKS_API_SERVER_BASE_PORT: "16650"
      FLOCI_SERVICES_EKS_API_SERVER_MAX_PORT: "16650"
      FLOCI_SERVICES_UI_ENABLED: "false"
networks:
  default:
    name: mcp-demo-floci
volumes:
  state:
